const app=document.querySelector('#app');
const sessionKey='zhijing_attempt';
let current=null,questionIndex=0,questionStarted=Date.now(),changes=0;
const icons={image:'🖼️',text:'💬',audio:'🎧',video:'🎬'};
async function api(url,options={}){const r=await fetch(url,{...options,headers:{'Content-Type':'application/json',...(current?{'X-Attempt-Token':current.token}:{}),...(options.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||'请求失败');return data}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function header(){return `<header class="topbar"><a class="brand" href="#home"><span class="brand-mark">知</span><span><b>知境</b><small>多模态情绪感知测评</small></span></a><nav class="topnav"><a href="#about">测评说明</a><a href="/admin">管理后台</a>${current?`<span class="user"><span>匿</span>${current.id.slice(-8)}</span>`:''}</nav></header>`}
function home(){app.innerHTML=header()+`<main class="content"><section class="hero"><div><div class="eyebrow">UNDERSTAND EMOTIONS · UNDERSTAND EACH OTHER</div><h1>读懂情绪，<br>看见更真实的<em>自己</em></h1><p>融合图像、文本、语音与视频情境，从识别、理解到推理，多维度探索你的情绪感知能力。全程匿名，结果仅用于个人能力反馈。</p><div class="actions"><button class="btn primary" id="start">${current?'继续测评':'开始匿名测评'} →</button><a class="btn" href="#about">了解测评</a></div></div><div class="hero-art"><div class="face"><div class="hair"></div><i class="eye l"></i><i class="eye r"></i><i class="mouth"></i></div><span class="float-tag t1">😊 情绪识别</span><span class="float-tag t2">💡 情境理解</span><span class="float-tag t3">◎ 多模态线索</span></div></section><div class="stats"><div class="stat"><small>测评维度</small><b>6</b><small>构建完整能力画像</small></div><div class="stat"><small>情绪类别</small><b>12+</b><small>基础与复合情绪</small></div><div class="stat"><small>题目模态</small><b>4</b><small>图文语音视频融合</small></div><div class="stat"><small>隐私保护</small><b>匿名</b><small>不收集个人身份信息</small></div></div></main>`;document.querySelector('#start').onclick=start}
function about(){app.innerHTML=header()+`<main class="content"><div class="page-head"><div><h1>测评说明</h1><p>开始前，请花一分钟了解作答方式</p></div></div><div class="grid"><div class="card span4"><h3>01 · 观察情境</h3><p class="report-copy">认真阅读文字或观察多媒体材料，综合人物表情、动作、语言与场景线索。</p></div><div class="card span4"><h3>02 · 判断情绪</h3><p class="report-copy">选择最符合情境的主导情绪，并用 1–5 级评价情绪表达强度。</p></div><div class="card span4"><h3>03 · 查看报告</h3><p class="report-copy">提交后立即获得总体表现、分项得分与规则化成长建议。</p></div><div class="card span12"><h3>隐私与用途</h3><p class="report-copy">系统将生成随机匿名编号，不收集姓名、手机号或学号。测评结果仅供个人成长和研究参考，不构成任何医学或心理诊断。</p><button class="btn primary" onclick="location.hash='home'">返回并开始测评</button></div></div></main>`}
async function start(){try{if(current){const a=await api(`/api/attempts/${current.id}`);if(a.status==='completed'){location.hash='report';return}current.data=a}else{const c=await api('/api/attempts',{method:'POST',body:'{}'});current={...c};localStorage.setItem(sessionKey,JSON.stringify(current));current.data=await api(`/api/attempts/${current.id}`)}questionIndex=Math.max(0,current.data.questions.findIndex(q=>!q.emotion&&!q.skipped));if(questionIndex<0)questionIndex=0;location.hash='assessment'}catch(e){toast(e.message)}}
function media(q){if(q.media_url){if(q.modality==='image')return `<div class="media-frame image-frame"><img class="question-media" src="${q.media_url}" alt="题目素材"></div>`;if(q.modality==='audio')return `<audio class="question-audio" controls src="${q.media_url}"></audio>`;if(q.modality==='video')return `<div class="media-frame video-frame"><video class="question-media" controls preload="metadata" src="${q.media_url}"></video></div>`}return `<div class="emoji">${icons[q.modality]}</div>`}
function assessment(){if(!current?.data)return start();const q=current.data.questions[questionIndex];questionStarted=Date.now();changes=0;app.innerHTML=header()+`<main class="assessment-wrap"><div class="page-head"><div><h1>多模态情绪感知测评</h1><p>匿名编号：${current.id}</p></div><span class="muted">答案将在切换题目时自动保存</span></div><div class="progress-row"><div class="progress"><div style="width:${(questionIndex+1)/current.data.questions.length*100}%"></div></div><b>${questionIndex+1} / ${current.data.questions.length}</b></div><div class="card question"><div class="mode-tabs">${['image','text','audio','video'].map(m=>`<span class="${m===q.modality?'active':''}">${icons[m]} ${{image:'图像',text:'文本',audio:'语音',video:'视频'}[m]}</span>`).join('')}</div><div class="stimulus"><div class="scene">${media(q)}<small class="muted">${q.title}</small><blockquote>${q.context}</blockquote><b>${q.prompt}</b></div></div><div class="answers"><div class="answer-box"><h4>选择最符合的情绪</h4><div class="emotions">${q.options.map(e=>`<button class="emotion ${q.emotion===e?'selected':''}" data-emotion="${e}">${e}</button>`).join('')}</div></div><div class="answer-box"><h4>判断情绪强度</h4><p class="muted">1 代表轻微，5 代表强烈</p><div class="slider-row"><span>轻微</span><input id="strength" type="range" min="1" max="5" value="${q.strength||3}"><b id="strengthVal">${q.strength||3}</b><span>强烈</span></div></div></div><div class="question-actions"><button class="btn" id="previous" ${questionIndex===0?'disabled':''}>← 上一题</button><div><button class="btn" id="skip">跳过</button> <button class="btn primary" id="next">${questionIndex===current.data.questions.length-1?'提交测评':'保存并下一题 →'}</button></div></div></div></main>`;
 document.querySelectorAll('[data-emotion]').forEach(b=>b.onclick=()=>{q.emotion=b.dataset.emotion;q.skipped=0;changes++;assessment()});const s=document.querySelector('#strength');s.oninput=()=>{q.strength=+s.value;changes++;document.querySelector('#strengthVal').textContent=s.value};document.querySelector('#skip').onclick=()=>save(true,1);document.querySelector('#next').onclick=()=>save(false,1);document.querySelector('#previous').onclick=()=>save(false,-1)}
async function save(skipped,direction){const q=current.data.questions[questionIndex];if(!skipped&&!q.emotion)return toast('请先选择一个情绪');try{await api(`/api/attempts/${current.id}/responses/${q.position}`,{method:'PUT',body:JSON.stringify({emotion:q.emotion,strength:q.strength||3,skipped,response_time_ms:(q.response_time_ms||0)+Date.now()-questionStarted,modification_count:(q.modification_count||0)+changes})});q.skipped=skipped?1:0;if(direction<0){questionIndex--;assessment();return}if(questionIndex<current.data.questions.length-1){questionIndex++;assessment()}else await submit()}catch(e){toast(e.message)}}
async function submit(){try{await api(`/api/attempts/${current.id}/submit`,{method:'POST',body:'{}'});current.data.status='completed';location.hash='report'}catch(e){toast(e.message)}}
function scoreClass(n){return n>=85?'优秀':n>=70?'良好':n>=60?'尚可':'需提升'}
async function report(){if(!current)return home();try{const r=await api(`/api/attempts/${current.id}/report`);const modes={image:'图像识别',text:'文本理解',audio:'语音识别',video:'视频识别'};app.innerHTML=header()+`<main class="content"><div class="page-head"><div><h1>个性化测评报告</h1><p>匿名编号 ${current.id}</p></div><button class="btn primary" onclick="window.print()">打印 / 保存 PDF</button></div><div class="grid"><div class="card span4"><small>综合得分</small><div class="report-score">${r.overall}<small>/100</small></div><span class="badge orange">${scoreClass(r.overall)}</span><div class="donut" style="background:conic-gradient(var(--orange) 0 ${r.overall}%,#eee ${r.overall}%)"></div></div><div class="card span8"><h3>总体评价</h3><p class="report-copy">${r.overall>=85?'你展现出优秀的多模态情绪感知能力，能够稳定地整合人物表情、语言与情境线索。':r.overall>=70?'你具备良好的情绪感知基础，在大多数日常互动中能够捕捉关键情绪线索。':'你已经具备一定的情绪识别基础，持续练习会帮助你更准确地理解复杂情境。'}</p><p class="report-copy">标签识别得分 ${r.label}，强度判断得分 ${r.strength}，平均每题反应时间 ${(r.average_response_ms/1000).toFixed(1)} 秒。</p></div><div class="card span7"><h3>各模态表现</h3><div class="bars">${Object.entries(r.by_modality).map(([k,v])=>`<div class="bar"><span>${modes[k]}</span><div class="track"><div class="fill" style="width:${v}%"></div></div><b>${v}</b></div>`).join('')}</div></div><div class="card span5"><h3>能力分项</h3><div class="bars"><div class="bar"><span>标签识别</span><div class="track"><div class="fill" style="width:${r.label}%"></div></div><b>${r.label}</b></div><div class="bar"><span>强度判断</span><div class="track"><div class="fill" style="width:${r.strength}%"></div></div><b>${r.strength}</b></div></div></div><div class="card span12"><h3>提升建议</h3><ul class="suggestions"><li>观察互动时，同时留意表情、措辞、语调和身体姿态，避免依赖单一线索。</li><li>遇到含蓄表达时，结合前后情境思考人物没有直接说出的感受。</li><li>在判断后寻找另一种合理解释，有助于减少先入为主造成的偏差。</li></ul><p class="muted">本报告由量化结果自动生成，仅供个人成长参考，不构成医疗诊断。</p><button class="btn" id="newAttempt">开始新的测评</button></div></div></main>`;document.querySelector('#newAttempt').onclick=()=>{localStorage.removeItem(sessionKey);current=null;location.hash='home'}}catch(e){toast(e.message);location.hash='home'}}
function route(){const p=location.hash.slice(1)||'home';({home,about,assessment,report}[p]||home)()}
try{current=JSON.parse(localStorage.getItem(sessionKey))}catch{}window.addEventListener('hashchange',route);route();
